### ISSUE TITLE
Total fuel burned not updating

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/homeassistant-plum-ecomax#45] opened 2023-11-11 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Sicen last update the Total fuel runed has stopped  changing on ecomax 920 device. I just ofund out that the graph im having on HA is flat. Restarting HS didnt help.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment] 2023-11-11 21:34
Hi,

Thank you for the feedback!

That's weird, since this sensor is not calculated by EM device. Instead it's platform independent and is calculated by the PyPlumIO and the integration, so if it runs for me, it should run for you. There was no change to this logic since forever...

These are steps that can be taken to troubleshoot the issue:
- does your fuel consumption sensor (in kg/h) work as total fuel burned calculator is based on it's value?
- is there messages like "Skipping outdated fuel consumption data, was (number) seconds old" in your log?
- when boiler is running, download integration diagnostics data a look for a `fuel_burned` key. It should have non-zero value.
- visit [Developer Tools -> Statistics](https://my.home-assistant.io/redirect/developer_statistics/), search for "fuel_total_burned" sensor and ensure that there's no problems reported.
- (optional) use plum_ecomax.calibrate_meter service in Developer Tools -> Services to manually set a value for the total_fuel_burned sensor. Value should be correctly set and no errors reported.

This will help you to pin the issue to specific component. Then we can decide on how to resolve it.

**Comment by svenlange2** [comment] 2023-11-11 21:46
Good that you mentioned its calculated in the plugin. And now as i hasve reset the HA I see it started to udate again. Problably something was not working between the restarts (it was ~2 weeks). The fuel consumption data that i derived from fuel level variable was updating as normal in between the restarts. I did not monitor fuel-burnt - so i dont know how that behaved. Thank you for the insight anyway. As it works now - case closed :)

**Comment by denpamusic** [comment] 2023-11-11 22:16
Thanks for heads up!

Great thinking with deriving burned fuel from fuel level btw. I was thinking about doing this, but ultimately decided against it, since it would require asking users how many kilos of fuel is 100%. Instead it is calculated by adding `current_fuel_consumption / (3600 * seconds_passed_since_last_received_consumption data)` to the total counter. Not very accurate method, I presume, since it deals with floats, but doesn't require any input from the user.

**Comment by svenlange2** [comment] 2023-11-16 17:03
It is broken again. It seems to be related to random disconnects of the rs485 dongle or reboots of the ecomax920 device itself. I dont know which as I only find out much later that the value has stopped updating. I know that i did power on/off cycle once for the device and now 5 days later i see that the value has been flat for 5 days on graph. I suggest to remove any checks on the logic calculating the value and take derivative in as fuel furn rate is detected. Last winter the deivce worked flawlessly for 5 months without any of such problems and i did numerous power cycles.

**Comment by denpamusic** [comment] 2023-11-16 18:10
Strange thing is there isn't any checks done by the integration. We simply extend [RestoreSensor](https://github.com/home-assistant/core/blob/b3e247d5f03c7d934ee96d361643545640402c84/homeassistant/components/sensor/__init__.py#L885C1-L885C1) with one function that adds value and nothing else: https://github.com/denpamusic/homeassistant-plum-ecomax/blob/e7dce23063f220a123c1ca9cb49dff7b5eb35fdd/custom_components/plum_ecomax/sensor.py#L474

I believe the issue it's probably introduced by one of the new HASS releases. There was no changes to fuel logic for well over the year in this integration or PyPlumIO.

I'll try to find an issue with `RestoreSensor`, but sadly chances are low, since it never happens to me even after power outages :(

**Comment by svenlange2** [comment] 2023-11-16 19:19
What kind of diagnostics data ? HASS log or something else ? (I need to catch it when its broken - i dont have it now as I restarted)

**Comment by denpamusic** [comment] 2023-11-16 20:10
The diagnostics, obtained via HomeAssistant's [built-in component](https://www.home-assistant.io/integrations/diagnostics/). Please follow steps below to obtain it, once sensor is broken. You can attach it via comments to this issue, or email it to me via denpa@denpa.pro. You can also open file with any text editor to review and remove any information you don't like me to see, although sensitive information like "UID" and device's IP address are already redacted.

1. Open the [integrations page](https://my.home-assistant.io/redirect/integrations/) in HASS and click the integration name "Plum ecoMAX".

![Screenshot showing one element of integration panel. Element is named "Plum ecoMAX"](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/42c2edea-0aba-449b-8021-69d909ea09ec)

2. Click three dots in the upper right corner and select "Download diagnostics".

![Modal menu, showing options for "Plum ecoMAX" integration. "Download diagnostics" is highlighted](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/75e464c6-6387-4999-9b02-1873023a7bcf)

Thanks again for you help!
Hopefully we will be able to figure out what's going on with this sensor.

**Comment by svenlange2** [comment] 2023-11-16 20:13
[config_entry-plum_ecomax-6b4fb62816ce81405437142431183f73.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/13382983/config_entry-plum_ecomax-6b4fb62816ce81405437142431183f73.json.txt)

This is the current state. I dont know if it makes sense to upload/send it again when it becomes broken ?

**Comment by denpamusic** [comment] 2023-11-16 20:25
Thank you!

Please do upload it again when it becomes broken.

See those values from your diagnostics below. `fuel_consumption` is your current boiler fuel consumption in kg/h, `fuel_burned` is difference counter. It contains the amount of fuel in kilograms since PyPlumIO last received `fuel_consumption` value (this frame is being sent about once per second or so). As you can see you boiler managed to burn about 1.3 grams of fuel during this period. These tiny value are being aggregated for 30 seconds and then sent to HASS, hence Total Burned Fuel counter in HASS updates once every 30 seconds.

If Total Burned Fuel in HASS breaks and we see `0` or `null` for "fuel_burned" in diagnostic data, we'll know for sure that the issue is with PyPlumIO or EM controller and not with integration or HASS itself. So we eliminate half of possible failure points just from this. 

```json
{
      "fuel_burned": 0.0013145052387522774,
      "fuel_consumption": 1.7245032787322998,
}
```

**Comment by denpamusic** [comment] 2024-01-05 03:00
I've probably found a root cause for this issue by accident during power outage...

When HomeAssistant (HASS) starts up and loads the integration, it calls `async_setup_entry()`, which tries to setup the integration and establish the connection. This mechanism retries `async_setup_entry()` call if previous one raises `ConfigEntryNotReady` exception. This behavior conflicts with PyPlumIO's own re-connection logic, which tries to reconnect every 20 seconds on any connection failure. As PyPlumIO doesn't know anything about HASS'es retry attempt, it keeps trying to reconnect every 20 seconds and becomes stale global task, which gets cancelled by HASS leading to incomplete setup.

This only happens, if HASS fails to connect to the converter during initial integration setup (i. e. after HASS restart), if connection to the converter is lost after the setup is done, the issue doesn't occur.

We'll fix it by closing PyPlumIO connection when raising `ConfigEntryNotReady` exception from `async_setup_entry()`. This way PyPlumIO wouldn't attempt to reconnect by itself after setup has failed, leaving this task to the HASS.

<details>
  <summary>homeassistant.log</summary>
  
  ```
    File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 74, in _connect
    reader, writer = await self._open_connection()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/timeout.py", line 21, in wrapper
    return await asyncio.wait_for(func(*args, **kwargs), timeout=seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 163, in _open_connection
    return await asyncio.open_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1045, in create_connection
    infos = await self._ensure_resolved(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 86, in _reconnect
    return await self._connect()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 81, in _connect
    raise ConnectionFailedError from connection_error
pyplumio.exceptions.ConnectionFailedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plum_ecomax/__init__.py", line 79, in async_setup_entry
    await connection.async_setup()
  File "/config/custom_components/plum_ecomax/connection.py", line 141, in async_setup
    await self.connect()
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 107, in connect
    await self._reconnect()
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 88, in _reconnect
    await self._connection_lost()
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 88, in _reconnect
    await self._connection_lost()
  File "/usr/local/lib/python3.11/site-packages/pyplumio/connection.py", line 88, in _reconnect
    await self._connection_lost()
  [Previous line repeated 8 more times]
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
```
</details>

**Comment by svenlange2** [comment] 2024-01-17 12:48
I see this in log now:

2024-01-17 14:32:41.245 WARNING (MainThread) [pyplumio.devices.ecomax] Skipping outdated fuel consumption data, was 247675 seconds old

15 minute gap in RS485 dongle connection to the Ecomax920 device. The seconds value is big as it happened some days ago already.

**Comment by denpamusic** [comment] 2024-01-17 14:45
Hi,

Thanks for the feedback!

I've fixed this issue in https://github.com/denpamusic/homeassistant-plum-ecomax/commit/4e03ad27bd73ceb81622f03c4e05b8347b70c820

Basically due to an error, integration creates multiple ecoMAX objects on reconnect, which blocks fuel counter from being updated correctly asall instances try to call same callback at the same time.

This fix will be released as part of v0.4.2.

**Closed** 2024-02-12 12:33 UTC
Labels: bug

**Comment by denpamusic** [comment] 2024-02-12 12:56
Hi again,

I found another issue with the fuel consumption tracker itself.

As I though, I just needed a bit of distraction from this project to find it...
It turns out it was really simple issue.
The https://github.com/denpamusic/homeassistant-plum-ecomax/commit/4e03ad27bd73ceb81622f03c4e05b8347b70c820 partially fixed this, by initiating full reconnect when setting up the integration, however if integration could recover without reconnecting the issue can still occur.

Previously when the consumption tracker encountered outdated fuel consumption data, it skipped processing it, which is good, but it also skipped setting a new current timestamp, which means that it has marked any frames received after received the outdated data, as outdated as well.

## Detailed example of the issue below:
current_timestamp = 0, frame_timestamp = 10, difference = 10 -> (processing fuel data, 10 seconds old)
current_timestamp = 10, frame_timestamp = 20, difference = 10 -> (processing fuel data, 10 seconds old)
current_timestamp = 20, frame_timestamp = 320, difference = 300  (outdated fuel data >= 300 seconds, skipping)
**On the next frames the issue happens, due to not setting updating timestamp in previous step.**
current_timestamp = **20** (should've been 320), frame_timestamp = 330, difference = 310 (fuel data incorrectly marked as outdated, despite it being only 10 seconds old)
current_timestamp = **20** (should've been 330), frame_timestamp = 340, difference = 320 (fuel data incorrectly marked as outdated, despite it still being only 10 seconds old)
and so on...

This has now been completely fixed in https://github.com/denpamusic/PyPlumIO/commit/79970c32a3231b0ff6b1270b78aa79a7fc87eaef with modification to the test case, so that it doesn't ever happen again.

I'll release v0.4.2 as minor that will incorporate this fix tomorrow, moving custom entities UI feature to v0.5.0.

Sorry for all the inconvenience caused, this was embarrassingly hard to track :(

**Comment by donis** [comment] 2026-04-02 16:15
Hey, I have the same issue happening right now. I can't exactly recall what was the cause, but there were some disconnects between ser2net and HA as I had to restart it then. All other sensors seem to work fine, but this one has stopped updating. Could there be some sort of lock that persists after restart? 

I tried to update to the latest beta, but that didn't resume gathering of total fuel burned. 

[config_entry-plum_ecomax-01KHA030YMD7AT4JGAED1S8N07(1).json](https://github.com/user-attachments/files/26442661/config_entry-plum_ecomax-01KHA030YMD7AT4JGAED1S8N07.1.json)
