### ISSUE TITLE
Fanning status display error

### ISSUE THREAD

**Issue by tusiek5** [denpamusic/homeassistant-plum-ecomax#19] opened 2023-02-03 09:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Error displaying fanning status, unknown status is displayed instead of this status.
I attach diagnostics generated during fanning.

Are the following available at this stage: return temperature, room temperature (ecoSter Touch), change of room temperature (ecoSter Touch), filling the pan; I don't have access to these parameters and they would be useful.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### My diagnostics data:

[config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json(1).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10577746/config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.1.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment] 2023-02-03 10:42
Hi,

Thank you for your feedback and especially diagnostics!👍

I'll updated states map to include state `23` as fanning and added return temperature sensor in aforementioned commits.

As for ecoSTERs, thermostat support using native HASS climate integration (example in screenshot below) is currently in development and will be included in the next version of the integration.

![Screenshot 2023-02-03 at 13-34-13 Overview – Home Assistant](https://user-images.githubusercontent.com/16575433/216579597-dcc1e297-43d2-4e1d-a0d0-cdadf692bf39.png)

Next version will be released in 5-6 days as 0.3.4-beta.1.
I'll be releasing it as beta first, due to sheer amount of changes. It'll be more comfortable for everybody to do more extensive testing, especially since I don't have ecoSTER myself.

**Comment by tusiek5** [comment] 2023-02-03 14:10
I've updated the integrations, I got errors when I run it and I can't read any parameters.

Error list:
Logger: pyplumio.devices.ecomax
Source: runner.py:120
First occurred: 15:03:24 (1 occurrences)
Last logged: 15:03:24

Request failed: could not request "alerts" with "REQUEST_ALERTS"


Logger: homeassistant.setup
Source: setup.py:340
First occurred: 15:03:13 (1 occurrences)
Last logged: 15:03:13

Unable to prepare setup for platform plum_ecomax.sensor: Platform not found (Exception importing custom_components.plum_ecomax.sensor).


Logger: homeassistant.loader
Source: custom_components/plum_ecomax/sensor.py:101
Integration: Plum ecoMAX (documentation, issues)
First occurred: 15:03:13 (1 occurrences)
Last logged: 15:03:13

Unexpected exception importing platform custom_components.plum_ecomax.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/plum_ecomax/sensor.py", line 101, in <module>
    EcomaxSensorEntityDescription(
TypeError: EcomaxSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'

**Comment by tusiek5** [comment] 2023-02-03 15:59
The problem is outdated, after restarting the computer everything works as it should.

**Comment by denpamusic** [comment] 2023-02-03 20:44
This is due to minimum required version of HASS. Main branch of the integration requires latest [2023.02.0 version of HASS](https://github.com/denpamusic/homeassistant-plum-ecomax/blob/main/hacs.json).

You probably didn't have your hass updated, hence it complained about nonexistent "native_precision" property.

Anyways, glad that you've got it working. If you encounter any other issue, don't hesitate to let me know. Although "main" branch is inherently unstable and there still be a lot of changes before aforementioned beta release of 0.3.4, so some issues is to be expected.

**Comment by denpamusic** [comment] 2023-02-05 16:44
homeassistant-plum-ecomax [v0.3.4-beta.1](https://github.com/denpamusic/homeassistant-plum-ecomax/releases/tag/v0.3.4-beta.1) just released. It includes support for ecoSTER thermostats, which hopefully should work with ecoSTER Touch too.

As for the last sensor that you requested. Ash pan status is not available in general controller data. It's might be available only in model-specific regdata under numeric key.

In order to add this sensor, we'll need to find which numeric key contains ash pan fullness.
Easiest way to do this, is to create two snapshots of diagnostics data.
1. Look at the controller screen and write down the ash pan fullness value. (e. g. 62%)
2. Download diagnostics from HASS.
3. Wait for a value to change and write it down again. (e. g. become 63%)
4. Download diagnostics from HASS again.
5. Send me both diagnostics and values that you're noted.
You can either do it under this issue or via denpa@denpa.pro.

You can also look at your regdata yourself and try to determine which key contains ash pan fullness, I'll paste it under spoiler below.

<details>
<summary>ecoMAX 860P3-O regdata from the diagnostics:</summary>

```
"1792": 3,
"1538": false,
"1536": true,
"1539": false,
"1": false,
"1541": true,
"1542": false,
"2": false,
"3": false,
"4": false,
"1544": true,
"1545": false,
"1546": false,
"5": false,
"222": false,
"1547": false,
"1548": false,
"1549": false,
"1550": false,
"1551": false,
"1552": false,
"6": false,
"223": false,
"1553": false,
"1554": false,
"1555": false,
"1556": false,
"1557": false,
"1558": false,
"7": false,
"14": 2348,
"11": 1279,
"10": 2534,
"9": 1977,
"15": 4095,
"13": 2109,
"8": 1712,
"16": 214,
"12": 2561,
"17": 182,
"18": 0,
"19": 0,
"20": 0,
"21": 0,
"22": 0,
"23": 0,
"24": 0,
"25": 0,
"26": 0,
"27": 0,
"28": 0,
"29": 0,
"1024": 58.2193603515625,
"1026": 24.595382690429688,
"1027": 1.8267631530761719,
"1025": 45.94587707519531,
"32": NaN,
"31": 49.66331481933594,
"1031": 37.54756164550781,
"33": NaN,
"30": 36.46145248413086,
"34": NaN,
"1028": NaN,
"1033": NaN,
"1032": NaN,
"1029": NaN,
"35": NaN,
"36": NaN,
"37": NaN,
"1035": NaN,
"1034": NaN,
"38": NaN,
"39": NaN,
"40": NaN,
"1280": 63,
"1282": 0,
"1283": 0,
"1281": 45,
"43": 0,
"42": 0,
"1287": 39,
"44": 0,
"41": 0,
"45": 0,
"1284": 0,
"1289": 36,
"1288": 36,
"1285": 0,
"46": 0,
"47": 0,
"48": 0,
"1291": 36,
"1290": 36,
"49": 0,
"50": 0,
"51": 0,
"58": 0,
"55": 0,
"54": 0,
"53": 0,
"59": 0,
"57": 0,
"52": 0,
"60": 0,
"56": 0,
"61": 0,
"62": 0,
"63": 8,
"64": 8,
"65": 0,
"66": 0,
"67": 0,
"70": 0,
"68": 8,
"69": 8,
"71": 0,
"72": 0,
"73": 0,
"80": false,
"77": false,
"76": false,
"75": false,
"81": true,
"79": false,
"74": false,
"82": true,
"78": false,
"83": true,
"84": true,
"85": true,
"86": true,
"87": true,
"88": true,
"89": true,
"90": true,
"91": true,
"92": true,
"93": true,
"94": true,
"95": true,
"96": false,
"109": 0,
"97": false,
"98": false,
"99": false,
"100": false,
"101": false,
"102": false,
"103": false,
"104": false,
"105": false,
"106": false,
"107": false,
"108": false,
"110": 8,
"111": false,
"112": false,
"2049": 0,
"113": false,
"114": false,
"115": false,
"116": false,
"117": false,
"118": false,
"119": false,
"120": false,
"121": false,
"122": false,
"123": false,
"126": false,
"125": false,
"124": false,
"127": false,
"128": false,
"129": false,
"130": false,
"131": false,
"132": false,
"133": false,
"2048": 2,
"134": false,
"135": false,
"136": true,
"137": false,
"138": false,
"139": false,
"140": true,
"145": 1.752262830734253,
"146": 0,
"206": false,
"207": false,
"208": true,
"209": false,
"210": false,
"211": false,
"212": true,
"204": 3.109999895095825,
"205": 17.889999389648438,
"142": false,
"1798": true,
"143": true,
"144": false,
"1543": false,
"1540": false,
"224": false,
"1794": 50,
"1793": 8.989108085632324,
"147": true,
"148": true,
"149": false,
"150": false,
"151": false,
"152": false,
"153": 14,
"154": 80,
"155": 1,
"156": 23,
"157": 0,
"158": 0,
"159": 0,
"160": 0,
"161": 0,
"162": 0,
"163": 0,
"164": 0,
"165": 0,
"166": false,
"167": false,
"168": false,
"169": false,
"170": false,
"171": 0,
"172": 0,
"173": 0.0,
"174": 0.0,
"213": 22.250240325927734,
"216": 22.5,
"219": 2,
"214": 0.0,
"217": 0.0,
"220": 255,
"215": 0.0,
"218": 0.0,
"221": 255,
"1795": 73,
"176": 0.0,
"178": 0,
"179": 0,
"180": NaN,
"181": 8.069148063659668,
"182": 600,
"183": 4462,
"184": 2053,
"185": 352,
"186": 2181,
"187": 22905.93359375,
"188": 10874,
"189": 176,
"190": 4083,
"191": "192.168.0.54",
"192": "255.255.255.0",
"193": "0.0.0.0",
"194": 1,
"195": "0.0.0.0",
"196": "255.255.255.0",
"197": "0.0.0.0",
"198": 1,
"199": 1,
"200": 100,
"201": 0,
"202": 0,
"203": "",
"225": NaN,
"226": 5.1027116775512695,
"227": 49,
"228": 691200000
```
</details>

**Comment by tusiek5** [comment] 2023-02-06 10:29
I have identified the parameter responsible for filling the ashtray ("227": 55,).
I will test the new version when I get home, the first attempt to run caused a problem with the connection. If I manage to connect correctly, I will let you know.

Some time ago I followed a thread on a certain forum where I was dealing with communication of Plum drivers and decrypting the communication frame.
In the excel file, I am sending a list that I managed to decode based on the data from the forum, maybe it will be helpful for you in further work.

[tabela ramki_EN.xls](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10662033/tabela.ramki_EN.xls)

**Comment by denpamusic** [comment] 2023-02-06 10:54
> I have identified the parameter responsible for filling the ashtray ("227": 55,). I will test the new version when I get home, the first attempt to run caused a problem with the connection. If I manage to connect correctly, I will let you know.

Got it. After release of v0.3.4 I'll implement product dependent regdata descriptors and add this parameter.

As for connection issue, this version didn't change anything related to connection process, so it's strange. Try to reload integration after HASS is already started, it might help. If it doesn't please check log contents, hopefully that help to identify what went wrong.

> Some time ago I followed a thread on a certain forum where I was dealing with communication of Plum drivers and decrypting the communication frame. In the excel file, I am sending a list that I managed to decode based on the data from the forum, maybe it will be helpful for you in further work.
> 
> [tabela ramki_EN.xls](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10662033/tabela.ramki_EN.xls)

Thanks for the table, even though it's a bit late. As I mentioned in readme, Plum ecoMAX was initially based on data provided by kind users on elektroda.pl and especially twkrol with his [econetanalyze](https://github.com/twkrol/econetanalyze/) project. However since then PyPlumIO grown past that. This table deals with byte offset positions of message to decode data, PyPlumIO actually doesn't need that to parse regdata messages, it's requests bytemap from controller itself via DataSchemaRequest and then decodes values based on this map.

The only problem with this is that Plum uses numerical keys which they convert to names on the remote server, so we common folk we'll need to find keys ourselves. What's more, that each controller model uses different keys...

Anyways thanks again for the heads up and sorry for boring you with the implementation details😅

**Comment by denpamusic** [comment] 2023-02-06 11:14
Actually, I think I already know why you might be having connection problem. From the log messages you provided before I noticed that your controller doesn't support REQUEST_ALERTS request. PyPlumIO will try 3 times waiting 5 seconds between tries, which amount to 15 seconds, but integration only waits for 10 seconds and then timeouts. I'll increased integration timeout, while simultaneously decreased PyPlumIO retry timeout so it should solve the connection issue that you were having.

When you get home, could you please try "main" branch instead of beta release. Thanks!

**Comment by tusiek5** [comment] 2023-02-06 12:08
I will check the main version, just tell me if I have to replay the entire integration or is it enough to replace some individual files?

**Comment by tusiek5** [comment] 2023-02-06 17:04
Thank you very much for your help, I reloaded the integration and everything works. I am testing the thermostat, the display of the current temperature seems to work correctly, but errors occur when setting a new value. After selecting a new temperature in HA, it is displayed correctly, while on ecoSter (room panel) a strange value appears, for example 199. Other times everything is fine; so far I do not see any diagram what could cause this error. I attach the diagnostics, the set temperature in HA 22.5, the room panel (ecoster) displays 48.1.

[config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json(7).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10665471/config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.7.txt)

**Comment by denpamusic** [comment] 2023-02-06 17:59
Thanks for diagnostics! There seems to be a problem with the way library is encoding the value before sending it to ecoSTER. I'll take a look at it and get back to you.

**Comment by denpamusic** [comment] 2023-02-06 19:17
I think I found the cause and fixed it.
Please re-download "main" and try again.

I also opened separate issue, so could you please reply with whether it works or not with the fix [there](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/20).

One problem per opened issue makes searching a lot easier in the future.

**Closed by denpamusic** 2023-02-06 19:17 UTC
Labels: bug
